// ============================================================================
// Current marketing copy, merged on top of landing-i18n.js.
//
// landing-i18n.js holds the twelve hand-written blocks as they were first
// generated. Everything whose wording has changed since then lives here, so a
// regeneration of that file cannot silently reinstate an old claim.
//
// What this layer exists to correct:
//
//   1. The product is the web app and nothing else. The download card points
//      at app.plately.eu; the Huawei AppGallery build was dropped.
//   2. The page needs a real <title> and description per language. They used
//      to be absent from the HTML entirely — see landing.js for why that was
//      the actual cause of the soft 404.
//   3. The old copy advertised "free forever", "no fees", "no premium tiers".
//      src/lib/plans.ts has paid tiers, so that claim was simply untrue. It is
//      replaced by the real three-tier price list; the figures and the limits
//      quoted per plan come from PLANS in that file.
//   4. "AI" was doing the work of a product description in the badge, the
//      title and the feature copy. What the page names now is what the app
//      actually does for the reader.
//
// Billing is in USD, so every locale quotes the same figure — only the
// sentence around it is translated.
// ============================================================================

(function () {
  'use strict';

  var WEB = {
    pl: {
      navFeatures: 'Możliwości', navPricing: 'Cennik', navDownload: 'Rozpocznij',
      badge: 'Dieta, nawodnienie i waga w jednym miejscu',
      lead: 'Plately zamienia zdjęcie posiłku w pełny rozkład makro, pilnuje nawodnienia i prowadzi Cię do docelowej wagi — z trenerem, który zna Twój kontekst.',
      statBLbl: 'Języków interfejsu',
      t1: 'Logowanie Google i ochrona na poziomie bazy',
      t2: 'Bez reklam i trackerów firm trzecich',
      t3: 'Eksport i usunięcie danych w każdej chwili',
      t4: 'Android, iOS, Windows i macOS',
      eyebrow: 'Możliwości',
      c1d: 'Fotografujesz talerz, a Plately rozpoznaje składniki i rozbija posiłek na kalorie, białko, węglowodany i tłuszcze.',
      c3d: 'Sen, stres, poziom aktywności, dieta i przeszkody — trener układa plan na podstawie Twojego kontekstu.',
      c4d: 'Logowanie Google i ochrona na poziomie bazy: nikt poza Tobą nie odczyta Twojego dziennika. Możesz też podłączyć własny klucz API.',
      prEyebrow: 'Cennik',
      prH2: 'Zacznij bez opłat, rozwiń kiedy zechcesz',
      prLead: 'Trzy plany i jasne limity. Reklam nie ma w żadnym z nich.',
      prPopular: 'Najczęściej wybierany', prPerMonth: 'miesięcznie',
      prFreeName: 'Start', prFreePrice: '$0', prFreeDesc: 'Codzienny dziennik posiłków, nawodnienia i wagi.', prFreeSub: 'Bez karty płatniczej i bez terminu.',
      prFreeF1: '4 analizy posiłku dziennie', prFreeF2: '2 wiadomości do trenera dziennie', prFreeF3: 'Odpowiedzi AI po ok. 20 s kolejki',
      prCtaFree: 'Załóż konto',
      prPremName: 'Premium', prPremPrice: '$6.99', prPremDesc: 'Dla osób prowadzących dziennik codziennie.', prPremSub: 'Lub $59 rocznie.',
      prPremF1: '8 analiz i 6 wiadomości do trenera dziennie', prPremF2: 'Odpowiedzi AI bez kolejki', prPremF3: '4 raporty AI z aktywności dziennie i własny kolor akcentu',
      prUltraName: 'Ultra', prUltraPrice: '$12.99', prUltraDesc: 'Najwyższe limity, dla codziennego, intensywnego dziennika.', prUltraSub: 'Lub $119 rocznie.',
      prUltraF1: 'Wszystko z planu Premium', prUltraF2: '16 analiz i 18 wiadomości do trenera dziennie',
      prCta: 'Wybierz plan',
      prNote: 'Ceny w dolarach amerykańskich. Plan zmienisz w ustawieniach konta. Każdy plan korzysta z tego samego modelu AI — plany płatne dają więcej odpowiedzi i bez czekania, nie dokładniejsze. Dane o aktywności (kroki, tętno, sen) wpisujesz ręcznie; Plately nie łączy się z zegarkiem.',
      ctaOpen: 'Otwórz aplikację',
            ctaLead: 'Plately działa w przeglądarce — na telefonie, tablecie i komputerze. Bez instalowania, w 12 językach.',
      footer: 'Plately — asystent diety, nawodnienia i kontroli wagi.',
      ftProduct: 'Produkt',
      ftLegalHead: 'Dokumenty', ftTerms: 'Regulamin', ftPrivacy: 'Polityka prywatności', ftSupport: 'Wsparcie',
      ftRights: 'Wszelkie prawa zastrzeżone.',
      metaTitle: 'Plately — asystent diety, nawodnienia i kontroli wagi',
      metaDesc: 'Plately zamienia zdjęcie posiłku w pełny rozkład makroskładników, pilnuje nawodnienia i prowadzi Cię do docelowej wagi. 12 języków, działa w przeglądarce na Androidzie, iOS, Windows i macOS.'
    },

    en: {
      navFeatures: 'Features', navPricing: 'Pricing', navDownload: 'Get started',
      badge: 'Diet, hydration and weight in one place',
      lead: 'Plately turns a photo of your plate into a full macro breakdown, keeps your hydration on track and guides you to your target weight — with a coach that knows your context.',
      statBLbl: 'Interface languages',
      t1: 'Google sign-in, database-level protection',
      t2: 'No ads, no third-party trackers',
      t3: 'Export or delete your data at any time',
      t4: 'Android, iOS, Windows and macOS',
      eyebrow: 'Capabilities',
      c1d: 'Snap your plate and Plately recognises the ingredients, splitting the meal into calories, protein, carbs and fat.',
      c3d: 'Sleep, stress, activity level, diet and obstacles — your coach builds a plan around your context.',
      c4d: 'Google sign-in and database-level protection: nobody but you can read your log. You can also connect your own API key.',
      prEyebrow: 'Pricing',
      prH2: 'Start at no cost, scale up when you need to',
      prLead: 'Three plans and clear limits. None of them carry ads.',
      prPopular: 'Most popular', prPerMonth: 'per month',
      prFreeName: 'Start', prFreePrice: '$0', prFreeDesc: 'A daily log for meals, hydration and weight.', prFreeSub: 'No card, no time limit.',
      prFreeF1: '4 meal analyses a day', prFreeF2: '2 coach messages a day', prFreeF3: 'AI answers after a ~20 s queue',
      prCtaFree: 'Create an account',
      prPremName: 'Premium', prPremPrice: '$6.99', prPremDesc: 'For logging every single day.', prPremSub: 'Or $59 a year.',
      prPremF1: '8 analyses and 6 coach messages a day', prPremF2: 'AI answers with no queue', prPremF3: '4 AI activity reports a day and a custom accent colour',
      prUltraName: 'Ultra', prUltraPrice: '$12.99', prUltraDesc: 'The highest limits, for a heavy daily diary.', prUltraSub: 'Or $119 a year.',
      prUltraF1: 'Everything in Premium', prUltraF2: '16 analyses and 18 coach messages a day',
      prCta: 'Choose plan',
      prNote: 'Prices in US dollars. You can change your plan in account settings. Every plan uses the same AI model — the paid ones give you more answers and no waiting, not more accurate ones. Activity figures (steps, heart rate, sleep) are typed in by hand; Plately does not connect to a watch.',
      ctaOpen: 'Open the app',
            ctaLead: 'Plately runs in your browser — on your phone, tablet and desktop. No install, in 12 languages.',
      footer: 'Plately — assistant for diet, hydration and weight.',
      ftProduct: 'Product',
      ftLegalHead: 'Legal', ftTerms: 'Terms of Service', ftPrivacy: 'Privacy Policy', ftSupport: 'Support',
      ftRights: 'All rights reserved.',
      metaTitle: 'Plately — diet, hydration and weight assistant',
      metaDesc: 'Plately turns a photo of your meal into a full macro breakdown, keeps an eye on your hydration and guides you to your target weight. 12 languages, runs in the browser on Android, iOS, Windows and macOS.'
    },

    de: {
      navFeatures: 'Funktionen', navPricing: 'Preise', navDownload: 'Loslegen',
      badge: 'Ernährung, Flüssigkeit und Gewicht an einem Ort',
      lead: 'Plately verwandelt ein Foto deines Tellers in eine vollständige Makro-Aufteilung, behält deine Flüssigkeitszufuhr im Blick und führt dich zum Zielgewicht — mit einem Coach, der deinen Kontext kennt.',
      statBLbl: 'Oberflächensprachen',
      t1: 'Google-Login und Schutz auf Datenbankebene',
      t2: 'Keine Werbung, keine Tracker Dritter',
      t3: 'Daten jederzeit exportieren oder löschen',
      t4: 'Android, iOS, Windows und macOS',
      eyebrow: 'Funktionen',
      c1d: 'Teller fotografieren — Plately erkennt die Zutaten und teilt die Mahlzeit in Kalorien, Protein, Kohlenhydrate und Fett auf.',
      c3d: 'Schlaf, Stress, Aktivität, Ernährung und Hürden — der Coach erstellt einen Plan auf Basis deines Kontexts.',
      c4d: 'Google-Login und Schutz auf Datenbankebene: niemand außer dir liest dein Tagebuch. Du kannst auch einen eigenen API-Schlüssel hinterlegen.',
      prEyebrow: 'Preise',
      prH2: 'Kostenlos starten, bei Bedarf erweitern',
      prLead: 'Drei Tarife mit klaren Limits. Werbung gibt es in keinem davon.',
      prPopular: 'Am beliebtesten', prPerMonth: 'pro Monat',
      prFreeName: 'Start', prFreePrice: '$0', prFreeDesc: 'Das tägliche Tagebuch für Mahlzeiten, Wasser und Gewicht.', prFreeSub: 'Ohne Karte, ohne Frist.',
      prFreeF1: '4 Mahlzeitenanalysen pro Tag', prFreeF2: '2 Coach-Nachrichten pro Tag', prFreeF3: 'KI-Antworten nach ~20 s Wartezeit',
      prCtaFree: 'Konto erstellen',
      prPremName: 'Premium', prPremPrice: '$6.99', prPremDesc: 'Für alle, die täglich protokollieren.', prPremSub: 'Oder $59 pro Jahr.',
      prPremF1: '8 Analysen und 6 Coach-Nachrichten pro Tag', prPremF2: 'KI-Antworten ohne Wartezeit', prPremF3: '4 KI-Aktivitätsberichte pro Tag und eigene Akzentfarbe',
      prUltraName: 'Ultra', prUltraPrice: '$12.99', prUltraDesc: 'Die höchsten Limits, für ein intensiv geführtes Tagebuch.', prUltraSub: 'Oder $119 pro Jahr.',
      prUltraF1: 'Alles aus Premium', prUltraF2: '16 Analysen und 18 Coach-Nachrichten pro Tag',
      prCta: 'Tarif wählen',
      prNote: 'Preise in US-Dollar. Den Tarif änderst du in den Kontoeinstellungen. Alle Tarife nutzen dasselbe KI-Modell — die bezahlten liefern mehr Antworten und ohne Wartezeit, nicht genauere. Aktivitätswerte (Schritte, Puls, Schlaf) gibst du von Hand ein; Plately verbindet sich nicht mit einer Uhr.',
      ctaOpen: 'App öffnen',
            ctaLead: 'Plately läuft im Browser — auf Handy, Tablet und Desktop. Ohne Installation, in 12 Sprachen.',
      footer: 'Plately — Assistent für Ernährung, Flüssigkeit und Gewicht.',
      ftProduct: 'Produkt',
      ftLegalHead: 'Rechtliches', ftTerms: 'AGB', ftPrivacy: 'Datenschutz', ftSupport: 'Support',
      ftRights: 'Alle Rechte vorbehalten.',
      metaTitle: 'Plately — Assistent für Ernährung, Flüssigkeit und Gewicht',
      metaDesc: 'Plately verwandelt ein Foto deiner Mahlzeit in eine vollständige Makro-Aufschlüsselung, achtet auf deine Flüssigkeitszufuhr und führt dich zum Zielgewicht. 12 Sprachen, im Browser auf Android, iOS, Windows und macOS.'
    },

    uk: {
      navFeatures: 'Можливості', navPricing: 'Тарифи', navDownload: 'Почати',
      badge: 'Харчування, вода і вага в одному місці',
      lead: 'Plately перетворює фото страви на повний розподіл макроелементів, стежить за водним балансом і веде вас до цільової ваги — з тренером, який знає ваш контекст.',
      statBLbl: 'Мов інтерфейсу',
      t1: 'Вхід через Google і захист на рівні бази',
      t2: 'Без реклами та сторонніх трекерів',
      t3: 'Експорт і видалення даних будь-коли',
      t4: 'Android, iOS, Windows і macOS',
      eyebrow: 'Можливості',
      c1d: 'Фотографуєте тарілку, а Plately розпізнає інгредієнти й розкладає страву на калорії, білки, вуглеводи та жири.',
      c3d: 'Сон, стрес, рівень активності, дієта та перешкоди — тренер складає план на основі вашого контексту.',
      c4d: 'Вхід через Google і захист на рівні бази: ніхто, крім вас, не прочитає ваш щоденник. Можна також підключити власний ключ API.',
      prEyebrow: 'Тарифи',
      prH2: 'Почніть безкоштовно, розширюйте за потреби',
      prLead: 'Три тарифи з чіткими лімітами. Реклами немає в жодному.',
      prPopular: 'Найпопулярніший', prPerMonth: 'на місяць',
      prFreeName: 'Старт', prFreePrice: '$0', prFreeDesc: 'Щоденник страв, води та ваги.', prFreeSub: 'Без картки й без терміну.',
      prFreeF1: '4 аналізи страв на день', prFreeF2: '2 повідомлення тренеру на день', prFreeF3: 'Відповіді ШІ після ~20 с черги',
      prCtaFree: 'Створити акаунт',
      prPremName: 'Premium', prPremPrice: '$6.99', prPremDesc: 'Для щоденного ведення щоденника.', prPremSub: 'Або $59 на рік.',
      prPremF1: '8 аналізів і 6 повідомлень тренеру на день', prPremF2: 'Відповіді ШІ без черги', prPremF3: '4 звіти ШІ про активність на день і власний колір акценту',
      prUltraName: 'Ultra', prUltraPrice: '$12.99', prUltraDesc: 'Найвищі ліміти — для щоденника, який ведуть інтенсивно.', prUltraSub: 'Або $119 на рік.',
      prUltraF1: 'Усе з тарифу Premium', prUltraF2: '16 аналізів і 18 повідомлень тренеру на день',
      prCta: 'Обрати тариф',
      prNote: 'Ціни в доларах США. Тариф змінюється в налаштуваннях акаунта. Усі тарифи використовують ту саму модель ШІ — платні дають більше відповідей і без очікування, а не точніші. Дані про активність (кроки, пульс, сон) ви вводите вручну; Plately не під’єднується до годинника.',
      ctaOpen: 'Відкрити застосунок',
            ctaLead: 'Plately працює у браузері — на телефоні, планшеті й компʼютері. Без встановлення, 12 мовами.',
      footer: 'Plately — асистент харчування, води та ваги.',
      ftProduct: 'Продукт',
      ftLegalHead: 'Документи', ftTerms: 'Умови користування', ftPrivacy: 'Політика конфіденційності', ftSupport: 'Підтримка',
      ftRights: 'Усі права захищено.',
      metaTitle: 'Plately — асистент харчування, води та ваги',
      metaDesc: 'Plately перетворює фото страви на повний розподіл макроелементів, стежить за водним балансом і веде вас до цільової ваги. 12 мов, у браузері на Android, iOS, Windows і macOS.'
    },

    ru: {
      navFeatures: 'Возможности', navPricing: 'Тарифы', navDownload: 'Начать',
      badge: 'Питание, вода и вес в одном месте',
      lead: 'Plately превращает фото блюда в полный разбор макронутриентов, следит за водным балансом и ведёт вас к целевому весу — с тренером, который знает ваш контекст.',
      statBLbl: 'Языков интерфейса',
      t1: 'Вход через Google и защита на уровне базы',
      t2: 'Без рекламы и сторонних трекеров',
      t3: 'Экспорт и удаление данных в любой момент',
      t4: 'Android, iOS, Windows и macOS',
      eyebrow: 'Возможности',
      c1d: 'Фотографируете тарелку, а Plately распознаёт ингредиенты и раскладывает блюдо на калории, белки, углеводы и жиры.',
      c3d: 'Сон, стресс, уровень активности, диета и препятствия — тренер составляет план на основе вашего контекста.',
      c4d: 'Вход через Google и защита на уровне базы: никто, кроме вас, не прочитает ваш дневник. Можно подключить собственный ключ API.',
      prEyebrow: 'Тарифы',
      prH2: 'Начните бесплатно, расширяйте по мере надобности',
      prLead: 'Три тарифа с понятными лимитами. Рекламы нет ни в одном.',
      prPopular: 'Самый популярный', prPerMonth: 'в месяц',
      prFreeName: 'Старт', prFreePrice: '$0', prFreeDesc: 'Ежедневный дневник еды, воды и веса.', prFreeSub: 'Без карты и без срока.',
      prFreeF1: '4 анализа блюд в день', prFreeF2: '2 сообщения тренеру в день', prFreeF3: 'Ответы ИИ после ~20 с очереди',
      prCtaFree: 'Создать аккаунт',
      prPremName: 'Premium', prPremPrice: '$6.99', prPremDesc: 'Для ежедневного ведения дневника.', prPremSub: 'Или $59 в год.',
      prPremF1: '8 анализов и 6 сообщений тренеру в день', prPremF2: 'Ответы ИИ без очереди', prPremF3: '4 отчёта ИИ об активности в день и свой цвет акцента',
      prUltraName: 'Ultra', prUltraPrice: '$12.99', prUltraDesc: 'Максимальные лимиты — для дневника, который ведут интенсивно.', prUltraSub: 'Или $119 в год.',
      prUltraF1: 'Всё из тарифа Premium', prUltraF2: '16 анализов и 18 сообщений тренеру в день',
      prCta: 'Выбрать тариф',
      prNote: 'Цены в долларах США. Тариф меняется в настройках аккаунта. Все тарифы используют одну и ту же модель ИИ — платные дают больше ответов и без ожидания, а не более точные. Данные об активности (шаги, пульс, сон) вы вводите вручную; Plately не подключается к часам.',
      ctaOpen: 'Открыть приложение',
            ctaLead: 'Plately работает в браузере — на телефоне, планшете и компьютере. Без установки, на 12 языках.',
      footer: 'Plately — ассистент питания, воды и веса.',
      ftProduct: 'Продукт',
      ftLegalHead: 'Документы', ftTerms: 'Условия использования', ftPrivacy: 'Политика конфиденциальности', ftSupport: 'Поддержка',
      ftRights: 'Все права защищены.',
      metaTitle: 'Plately — ассистент питания, воды и веса',
      metaDesc: 'Plately превращает фото блюда в полный разбор макронутриентов, следит за водным балансом и ведёт вас к целевому весу. 12 языков, в браузере на Android, iOS, Windows и macOS.'
    },

    fr: {
      navFeatures: 'Fonctionnalités', navPricing: 'Tarifs', navDownload: 'Commencer',
      badge: 'Alimentation, hydratation et poids au même endroit',
      lead: 'Plately transforme la photo de votre assiette en répartition complète des macros, surveille votre hydratation et vous guide vers votre poids cible — avec un coach qui connaît votre contexte.',
      statBLbl: 'Langues d’interface',
      t1: 'Connexion Google, protection au niveau de la base',
      t2: 'Ni publicité ni traceurs tiers',
      t3: 'Export et suppression des données à tout moment',
      t4: 'Android, iOS, Windows et macOS',
      eyebrow: 'Fonctionnalités',
      c1d: 'Photographiez votre assiette : Plately reconnaît les ingrédients et répartit le repas en calories, protéines, glucides et lipides.',
      c3d: 'Sommeil, stress, niveau d’activité, régime et obstacles — le coach construit un plan à partir de votre contexte.',
      c4d: 'Connexion Google et protection au niveau de la base : personne d’autre que vous ne lit votre journal. Vous pouvez aussi utiliser votre propre clé API.',
      prEyebrow: 'Tarifs',
      prH2: 'Commencez sans frais, évoluez quand vous voulez',
      prLead: 'Trois formules, des limites claires. Aucune ne contient de publicité.',
      prPopular: 'Le plus choisi', prPerMonth: 'par mois',
      prFreeName: 'Start', prFreePrice: '$0', prFreeDesc: 'Le journal quotidien des repas, de l’eau et du poids.', prFreeSub: 'Sans carte et sans échéance.',
      prFreeF1: '4 analyses de repas par jour', prFreeF2: '2 messages au coach par jour', prFreeF3: 'Réponses de l’IA après ~20 s de file',
      prCtaFree: 'Créer un compte',
      prPremName: 'Premium', prPremPrice: '$6.99', prPremDesc: 'Pour un suivi quotidien.', prPremSub: 'Ou $59 par an.',
      prPremF1: '8 analyses et 6 messages au coach par jour', prPremF2: 'Réponses de l’IA sans file d’attente', prPremF3: '4 rapports d’IA sur l’activité par jour et une couleur d’accent personnalisée',
      prUltraName: 'Ultra', prUltraPrice: '$12.99', prUltraDesc: 'Les limites les plus élevées, pour un journal tenu intensivement.', prUltraSub: 'Ou $119 par an.',
      prUltraF1: 'Tout le contenu de Premium', prUltraF2: '16 analyses et 18 messages au coach par jour',
      prCta: 'Choisir cette formule',
      prNote: 'Prix en dollars américains. Vous changez de formule dans les réglages du compte. Toutes les formules utilisent le même modèle d’IA — les payantes donnent plus de réponses et sans attente, pas des réponses plus précises. Les données d’activité (pas, fréquence cardiaque, sommeil) se saisissent à la main ; Plately ne se connecte pas à une montre.',
      ctaOpen: 'Ouvrir l’application',
            ctaLead: 'Plately fonctionne dans le navigateur — sur téléphone, tablette et ordinateur. Sans installation, en 12 langues.',
      footer: 'Plately — assistant d’alimentation, d’hydratation et de poids.',
      ftProduct: 'Produit',
      ftLegalHead: 'Documents', ftTerms: 'Conditions d’utilisation', ftPrivacy: 'Politique de confidentialité', ftSupport: 'Assistance',
      ftRights: 'Tous droits réservés.',
      metaTitle: 'Plately — assistant d’alimentation, d’hydratation et de poids',
      metaDesc: 'Plately transforme la photo d’un repas en répartition complète des macros, surveille votre hydratation et vous guide vers votre poids cible. 12 langues, dans le navigateur sur Android, iOS, Windows et macOS.'
    },

    it: {
      navFeatures: 'Funzioni', navPricing: 'Prezzi', navDownload: 'Inizia',
      badge: 'Dieta, idratazione e peso in un unico posto',
      lead: 'Plately trasforma la foto del piatto in una ripartizione completa dei macronutrienti, tiene d’occhio l’idratazione e ti guida al peso desiderato — con un coach che conosce il tuo contesto.',
      statBLbl: 'Lingue dell’interfaccia',
      t1: 'Accesso Google e protezione a livello di database',
      t2: 'Nessuna pubblicità, nessun tracker di terze parti',
      t3: 'Esportazione ed eliminazione dei dati in qualsiasi momento',
      t4: 'Android, iOS, Windows e macOS',
      eyebrow: 'Funzioni',
      c1d: 'Fotografi il piatto e Plately riconosce gli ingredienti, dividendo il pasto in calorie, proteine, carboidrati e grassi.',
      c3d: 'Sonno, stress, livello di attività, dieta e ostacoli — il coach costruisce un piano sul tuo contesto.',
      c4d: 'Accesso con Google e protezione a livello di database: nessuno tranne te legge il tuo diario. Puoi anche collegare la tua chiave API.',
      prEyebrow: 'Prezzi',
      prH2: 'Inizia senza spese, cresci quando serve',
      prLead: 'Tre piani con limiti chiari. In nessuno di questi c’è pubblicità.',
      prPopular: 'Il più scelto', prPerMonth: 'al mese',
      prFreeName: 'Start', prFreePrice: '$0', prFreeDesc: 'Il diario quotidiano di pasti, acqua e peso.', prFreeSub: 'Senza carta e senza scadenza.',
      prFreeF1: '4 analisi dei pasti al giorno', prFreeF2: '2 messaggi al coach al giorno', prFreeF3: 'Risposte IA dopo ~20 s di coda',
      prCtaFree: 'Crea un account',
      prPremName: 'Premium', prPremPrice: '$6.99', prPremDesc: 'Per chi tiene il diario ogni giorno.', prPremSub: 'Oppure $59 all’anno.',
      prPremF1: '8 analisi e 6 messaggi al coach al giorno', prPremF2: 'Risposte IA senza coda', prPremF3: '4 report IA sull’attività al giorno e un colore d’accento personalizzato',
      prUltraName: 'Ultra', prUltraPrice: '$12.99', prUltraDesc: 'I limiti più alti, per un diario tenuto intensamente.', prUltraSub: 'Oppure $119 all’anno.',
      prUltraF1: 'Tutto quello che c’è in Premium', prUltraF2: '16 analisi e 18 messaggi al coach al giorno',
      prCta: 'Scegli il piano',
      prNote: 'Prezzi in dollari statunitensi. Il piano si cambia nelle impostazioni dell’account. Tutti i piani usano lo stesso modello IA — quelli a pagamento danno più risposte e senza attesa, non più precise. I dati di attività (passi, battito, sonno) si inseriscono a mano; Plately non si collega a un orologio.',
      ctaOpen: 'Apri l’app',
            ctaLead: 'Plately funziona nel browser — su telefono, tablet e computer. Senza installazione, in 12 lingue.',
      footer: 'Plately — assistente per dieta, idratazione e peso.',
      ftProduct: 'Prodotto',
      ftLegalHead: 'Documenti', ftTerms: 'Termini di servizio', ftPrivacy: 'Informativa sulla privacy', ftSupport: 'Assistenza',
      ftRights: 'Tutti i diritti riservati.',
      metaTitle: 'Plately — assistente per dieta, idratazione e peso',
      metaDesc: 'Plately trasforma la foto di un pasto in una ripartizione completa dei macronutrienti, tiene d’occhio l’idratazione e ti guida al peso desiderato. 12 lingue, nel browser su Android, iOS, Windows e macOS.'
    },

    es: {
      navFeatures: 'Funciones', navPricing: 'Precios', navDownload: 'Empezar',
      badge: 'Dieta, hidratación y peso en un solo sitio',
      lead: 'Plately convierte la foto de tu plato en un desglose completo de macronutrientes, vigila tu hidratación y te guía hasta tu peso objetivo — con un entrenador que conoce tu contexto.',
      statBLbl: 'Idiomas de la interfaz',
      t1: 'Acceso con Google y protección a nivel de base de datos',
      t2: 'Sin anuncios ni rastreadores de terceros',
      t3: 'Exporta o borra tus datos cuando quieras',
      t4: 'Android, iOS, Windows y macOS',
      eyebrow: 'Funciones',
      c1d: 'Fotografías el plato y Plately reconoce los ingredientes, repartiendo la comida en calorías, proteínas, carbohidratos y grasas.',
      c3d: 'Sueño, estrés, nivel de actividad, dieta y obstáculos — el entrenador arma un plan según tu contexto.',
      c4d: 'Acceso con Google y protección a nivel de base de datos: nadie salvo tú lee tu diario. También puedes conectar tu propia clave de API.',
      prEyebrow: 'Precios',
      prH2: 'Empieza sin coste y amplía cuando lo necesites',
      prLead: 'Tres planes con límites claros. Ninguno lleva anuncios.',
      prPopular: 'El más elegido', prPerMonth: 'al mes',
      prFreeName: 'Start', prFreePrice: '$0', prFreeDesc: 'Diario de comidas, agua y peso.', prFreeSub: 'Sin tarjeta y sin plazo.',
      prFreeF1: '4 análisis de comidas al día', prFreeF2: '2 mensajes al entrenador al día', prFreeF3: 'Respuestas de IA tras ~20 s de cola',
      prCtaFree: 'Crear una cuenta',
      prPremName: 'Premium', prPremPrice: '$6.99', prPremDesc: 'Para quien registra cada día.', prPremSub: 'O $59 al año.',
      prPremF1: '8 análisis y 6 mensajes al entrenador al día', prPremF2: 'Respuestas de IA sin cola', prPremF3: '4 informes de IA de actividad al día y un color de acento personalizado',
      prUltraName: 'Ultra', prUltraPrice: '$12.99', prUltraDesc: 'Los límites más altos, para un diario intenso a diario.', prUltraSub: 'O $119 al año.',
      prUltraF1: 'Todo lo de Premium', prUltraF2: '16 análisis y 18 mensajes al entrenador al día',
      prCta: 'Elegir plan',
      prNote: 'Precios en dólares estadounidenses. El plan se cambia en los ajustes de la cuenta. Todos los planes usan el mismo modelo de IA: los de pago dan más respuestas y sin esperas, no más precisas. Los datos de actividad (pasos, pulso, sueño) se escriben a mano; Plately no se conecta a un reloj.',
      ctaOpen: 'Abrir la app',
            ctaLead: 'Plately funciona en el navegador — en el móvil, la tablet y el ordenador. Sin instalación, en 12 idiomas.',
      footer: 'Plately — asistente de dieta, hidratación y peso.',
      ftProduct: 'Producto',
      ftLegalHead: 'Documentos', ftTerms: 'Términos del servicio', ftPrivacy: 'Política de privacidad', ftSupport: 'Soporte',
      ftRights: 'Todos los derechos reservados.',
      metaTitle: 'Plately — asistente de dieta, hidratación y peso',
      metaDesc: 'Plately convierte la foto de una comida en un desglose completo de macronutrientes, vigila tu hidratación y te guía hasta tu peso objetivo. 12 idiomas, en el navegador en Android, iOS, Windows y macOS.'
    },

    pt: {
      navFeatures: 'Funcionalidades', navPricing: 'Preços', navDownload: 'Começar',
      badge: 'Dieta, hidratação e peso num só lugar',
      lead: 'O Plately transforma a foto do teu prato num desdobramento completo de macronutrientes, cuida da tua hidratação e guia-te até ao peso desejado — com um treinador que conhece o teu contexto.',
      statBLbl: 'Idiomas da interface',
      t1: 'Início de sessão Google e proteção ao nível da base de dados',
      t2: 'Sem publicidade e sem rastreadores de terceiros',
      t3: 'Exportação e eliminação de dados a qualquer momento',
      t4: 'Android, iOS, Windows e macOS',
      eyebrow: 'Funcionalidades',
      c1d: 'Fotografas o prato e o Plately reconhece os ingredientes, dividindo a refeição em calorias, proteínas, hidratos de carbono e gorduras.',
      c3d: 'Sono, stress, nível de atividade, dieta e obstáculos — o treinador monta um plano a partir do teu contexto.',
      c4d: 'Início de sessão Google e proteção ao nível da base de dados: ninguém além de ti lê o teu diário. Também podes ligar a tua própria chave de API.',
      prEyebrow: 'Preços',
      prH2: 'Começa sem custos e cresce quando precisares',
      prLead: 'Três planos com limites claros. Nenhum deles tem publicidade.',
      prPopular: 'O mais escolhido', prPerMonth: 'por mês',
      prFreeName: 'Start', prFreePrice: '$0', prFreeDesc: 'Diário de refeições, água e peso.', prFreeSub: 'Sem cartão e sem prazo.',
      prFreeF1: '4 análises de refeições por dia', prFreeF2: '2 mensagens ao treinador por dia', prFreeF3: 'Respostas de IA após ~20 s de fila',
      prCtaFree: 'Criar conta',
      prPremName: 'Premium', prPremPrice: '$6.99', prPremDesc: 'Para quem regista todos os dias.', prPremSub: 'Ou $59 por ano.',
      prPremF1: '8 análises e 6 mensagens ao treinador por dia', prPremF2: 'Respostas de IA sem fila', prPremF3: '4 relatórios de IA de atividade por dia e uma cor de destaque personalizada',
      prUltraName: 'Ultra', prUltraPrice: '$12.99', prUltraDesc: 'Os limites mais altos, para um diário mantido intensamente.', prUltraSub: 'Ou $119 por ano.',
      prUltraF1: 'Tudo o que está no Premium', prUltraF2: '16 análises e 18 mensagens ao treinador por dia',
      prCta: 'Escolher plano',
      prNote: 'Preços em dólares americanos. O plano muda-se nas definições da conta. Todos os planos usam o mesmo modelo de IA — os pagos dão mais respostas e sem espera, não mais exatas. Os dados de atividade (passos, batimentos, sono) são introduzidos à mão; o Plately não se liga a um relógio.',
      ctaOpen: 'Abrir a aplicação',
            ctaLead: 'O Plately funciona no navegador — no telemóvel, tablet e computador. Sem instalação, em 12 idiomas.',
      footer: 'Plately — assistente de dieta, hidratação e peso.',
      ftProduct: 'Produto',
      ftLegalHead: 'Documentos', ftTerms: 'Termos de utilização', ftPrivacy: 'Política de privacidade', ftSupport: 'Suporte',
      ftRights: 'Todos os direitos reservados.',
      metaTitle: 'Plately — assistente de dieta, hidratação e peso',
      metaDesc: 'O Plately transforma a foto de uma refeição num desdobramento completo de macronutrientes, cuida da tua hidratação e guia-te até ao peso desejado. 12 idiomas, no navegador em Android, iOS, Windows e macOS.'
    },

    ja: {
      navFeatures: '機能', navPricing: '料金', navDownload: '始める',
      badge: '食事・水分・体重をひとつに',
      lead: 'Plately は食事の写真からマクロ栄養素を算出し、水分補給を見守り、目標体重まで導きます。あなたの状況を把握したコーチが付きます。',
      statBLbl: '対応言語',
      t1: 'Google ログインとデータベースレベルの保護',
      t2: '広告も第三者トラッカーもなし',
      t3: 'データのエクスポートと削除はいつでも',
      t4: 'Android・iOS・Windows・macOS',
      eyebrow: '機能',
      c1d: 'お皿を撮るだけで、Plately が食材を認識し、カロリー・タンパク質・炭水化物・脂質に分解します。',
      c3d: '睡眠、ストレス、活動量、食事、つまずき — コーチがあなたの状況に合わせて計画を組み立てます。',
      c4d: 'Google ログインとデータベースレベルの保護により、記録を読めるのはあなただけです。独自の API キーを使うこともできます。',
      prEyebrow: '料金',
      prH2: '無料で始めて、必要になったら広げる',
      prLead: '3つのプランと明確な上限。広告はどのプランにもありません。',
      prPopular: '人気', prPerMonth: '月額',
      prFreeName: 'Start', prFreePrice: '$0', prFreeDesc: '食事・水分・体重の毎日の記録。', prFreeSub: 'カード登録も期限もなし。',
      prFreeF1: '食事分析は1日4回', prFreeF2: 'コーチへのメッセージは1日2件', prFreeF3: 'AIの回答は約20秒の順番待ちのあと',
      prCtaFree: 'アカウントを作成',
      prPremName: 'Premium', prPremPrice: '$6.99', prPremDesc: '毎日記録する方に。', prPremSub: 'または年額 $59。',
      prPremF1: '1日8回の分析とコーチへのメッセージ6件', prPremF2: 'AIの回答は順番待ちなし', prPremF3: '活動のAIレポート1日4回と、アクセントカラーの変更',
      prUltraName: 'Ultra', prUltraPrice: '$12.99', prUltraDesc: '毎日しっかり記録する方向けの、最上位の上限。', prUltraSub: 'または年額 $119。',
      prUltraF1: 'Premium のすべて', prUltraF2: '1日16回の分析とコーチへのメッセージ18件',
      prCta: 'プランを選ぶ',
      prNote: '価格は米ドルです。プランはアカウント設定で変更できます。すべてのプランが同じAIモデルを使います。有料プランで増えるのは回数と速さであり、精度ではありません。活動データ（歩数・心拍・睡眠）は手入力で、Plately は時計とは連携しません。',
      ctaOpen: 'アプリを開く',
            ctaLead: 'Plately はブラウザで動きます — スマホ、タブレット、パソコンで。インストール不要、12言語対応。',
      footer: 'Plately — 食事・水分・体重のアシスタント。',
      ftProduct: 'プロダクト',
      ftLegalHead: '規約', ftTerms: '利用規約', ftPrivacy: 'プライバシーポリシー', ftSupport: 'サポート',
      ftRights: '無断転載を禁じます。',
      metaTitle: 'Plately — 食事・水分・体重を管理するアシスタント',
      metaDesc: 'Plately は食事の写真からマクロ栄養素を算出し、水分補給を見守り、目標体重まで導きます。12言語対応、Android・iOS・Windows・macOS のブラウザで動作します。'
    },

    zh: {
      navFeatures: '功能', navPricing: '价格', navDownload: '开始使用',
      badge: '饮食、饮水与体重，集中在一处',
      lead: 'Plately 把一张餐食照片变成完整的宏量营养素分析，帮你关注饮水，并引导你达到目标体重 —— 由了解你情况的教练陪伴。',
      statBLbl: '界面语言',
      t1: 'Google 登录与数据库级保护',
      t2: '没有广告，没有第三方追踪',
      t3: '随时导出或删除数据',
      t4: 'Android、iOS、Windows 与 macOS',
      eyebrow: '功能',
      c1d: '拍下餐盘，Plately 识别食材，并把这餐拆成热量、蛋白质、碳水和脂肪。',
      c3d: '睡眠、压力、活动量、饮食与阻碍 —— 教练依据你的情况制定计划。',
      c4d: 'Google 登录与数据库级保护：除你之外无人能读取你的记录。你也可以接入自己的 API 密钥。',
      prEyebrow: '价格',
      prH2: '免费开始，需要时再升级',
      prLead: '三种方案，限额清晰。任何一种都没有广告。',
      prPopular: '最多人选择', prPerMonth: '每月',
      prFreeName: 'Start', prFreePrice: '$0', prFreeDesc: '每天记录餐食、饮水与体重。', prFreeSub: '无需银行卡，也没有期限。',
      prFreeF1: '每天 4 次餐食分析', prFreeF2: '每天 2 条教练消息', prFreeF3: 'AI 回复需约 20 秒排队',
      prCtaFree: '创建账户',
      prPremName: 'Premium', prPremPrice: '$6.99', prPremDesc: '适合每天记录的人。', prPremSub: '或每年 $59。',
      prPremF1: '每天 8 次分析与 6 条教练消息', prPremF2: 'AI 回复无需排队', prPremF3: '每天 4 份活动 AI 报告，并可自定义强调色',
      prUltraName: 'Ultra', prUltraPrice: '$12.99', prUltraDesc: '最高限额，适合每天大量记录。', prUltraSub: '或每年 $119。',
      prUltraF1: '包含 Premium 的全部内容', prUltraF2: '每天 16 次分析与 18 条教练消息',
      prCta: '选择方案',
      prNote: '价格以美元计价。方案可在账户设置中更改。所有方案使用同一个 AI 模型——付费方案带来的是更多次数和免排队，而不是更高的准确度。活动数据（步数、心率、睡眠）需手动输入，Plately 不与手表连接。',
      ctaOpen: '打开应用',
            ctaLead: 'Plately 在浏览器中运行 — 手机、平板和电脑都可以。无需安装，支持 12 种语言。',
      footer: 'Plately — 饮食、饮水与体重助手。',
      ftProduct: '产品',
      ftLegalHead: '条款', ftTerms: '服务条款', ftPrivacy: '隐私政策', ftSupport: '支持',
      ftRights: '保留所有权利。',
      metaTitle: 'Plately — 饮食、饮水与体重助手',
      metaDesc: 'Plately 把一张餐食照片变成完整的宏量营养素分析，帮你关注饮水，并引导你达到目标体重。支持 12 种语言，可在 Android、iOS、Windows 与 macOS 的浏览器中使用。'
    },

    ko: {
      navFeatures: '기능', navPricing: '요금제', navDownload: '시작하기',
      badge: '식단, 수분, 체중을 한곳에서',
      lead: 'Plately는 식사 사진을 완전한 매크로 영양소 분석으로 바꾸고, 수분 섭취를 챙기며, 목표 체중까지 이끌어 줍니다 — 당신의 상황을 아는 코치와 함께.',
      statBLbl: '지원 언어',
      t1: 'Google 로그인과 데이터베이스 수준 보호',
      t2: '광고와 제3자 트래커 없음',
      t3: '언제든 데이터 내보내기와 삭제',
      t4: 'Android, iOS, Windows, macOS',
      eyebrow: '기능',
      c1d: '접시를 찍으면 Plately가 재료를 인식해 열량, 단백질, 탄수화물, 지방으로 나눕니다.',
      c3d: '수면, 스트레스, 활동량, 식단, 걸림돌 — 코치가 당신의 상황에 맞춰 계획을 세웁니다.',
      c4d: 'Google 로그인과 데이터베이스 수준 보호로 기록은 본인만 볼 수 있습니다. 직접 발급한 API 키도 연결할 수 있습니다.',
      prEyebrow: '요금제',
      prH2: '무료로 시작하고 필요할 때 확장하세요',
      prLead: '세 가지 요금제와 명확한 한도. 어느 요금제에도 광고는 없습니다.',
      prPopular: '가장 많이 선택', prPerMonth: '월',
      prFreeName: 'Start', prFreePrice: '$0', prFreeDesc: '식사, 수분, 체중의 매일 기록.', prFreeSub: '카드도 기한도 없습니다.',
      prFreeF1: '하루 4회 식사 분석', prFreeF2: '하루 2개 코치 메시지', prFreeF3: 'AI 답변은 약 20초 대기 후',
      prCtaFree: '계정 만들기',
      prPremName: 'Premium', prPremPrice: '$6.99', prPremDesc: '매일 기록하는 분께.', prPremSub: '또는 연 $59.',
      prPremF1: '하루 8회 분석과 코치 메시지 6개', prPremF2: 'AI 답변 대기 없음', prPremF3: '하루 4개 활동 AI 리포트와 원하는 강조 색상',
      prUltraName: 'Ultra', prUltraPrice: '$12.99', prUltraDesc: '매일 꼼꼼히 기록하는 사람을 위한 최고 한도.', prUltraSub: '또는 연 $119.',
      prUltraF1: 'Premium의 모든 기능', prUltraF2: '하루 16회 분석과 코치 메시지 18개',
      prCta: '요금제 선택',
      prNote: '가격은 미국 달러입니다. 요금제는 계정 설정에서 변경할 수 있습니다. 모든 요금제가 같은 AI 모델을 사용합니다. 유료 요금제가 늘려 주는 것은 횟수와 속도이며 정확도가 아닙니다. 활동 데이터(걸음 수, 심박수, 수면)는 직접 입력하며, Plately는 시계와 연동되지 않습니다.',
      ctaOpen: '앱 열기',
            ctaLead: 'Plately는 브라우저에서 실행됩니다 — 휴대폰, 태블릿, 데스크톱에서. 설치 없이, 12개 언어로.',
      footer: 'Plately — 식단, 수분, 체중 어시스턴트.',
      ftProduct: '제품',
      ftLegalHead: '약관', ftTerms: '이용약관', ftPrivacy: '개인정보 처리방침', ftSupport: '지원',
      ftRights: '모든 권리 보유.',
      metaTitle: 'Plately — 식단, 수분, 체중 어시스턴트',
      metaDesc: 'Plately는 식사 사진을 완전한 매크로 영양소 분석으로 바꾸고, 수분 섭취를 챙기며, 목표 체중까지 이끌어 줍니다. 12개 언어, Android·iOS·Windows·macOS 브라우저에서 작동합니다.'
    }
  };

  var dict = (window.PLATELY_I18N = window.PLATELY_I18N || {});
  Object.keys(WEB).forEach(function (code) {
    dict[code] = Object.assign({}, dict[code], WEB[code]);
  });
})();
